# SPDX-FileCopyrightText: 2022 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
# SPDX-FileCopyrightText: 2021 Belcan Advanced Solution
#
# SPDX-License-Identifier: MIT
---
services:
  bart:
    image: ghcr.io/belcan-as/bart:dev
    build:
      dockerfile: Dockerfile
      context: "."
    environment:
      PROPERTIES_FILE: /bart.properties
    configs:
      - source: bart
        target: /bart.properties
    volumes:
      - alfresco_root:/opt/alfresco
      - ./config-example/bart:/root/config # ADD BART Config
      - bart_keys:/keys

configs:
  bart:
    file: ./config-example/bart/bart.properties

volumes:
  alfresco_root:
  bart_keys:
