version: "2"
services:
  alfresco-backup-and-recovery-tool:
    image: registry2.lagoni.co.uk/lagoni-engineering/alfresco-backup-and-recovery-tool:dev
    build:
      dockerfile: Dockerfile
      context: "."
    environment:
      ALFBRT_PATH: /root/config
      RESTOREDIR: /restore
    volumes:
      - alfresco_root:/opt/alfresco
      - ./config-example/bart:/root/config # ADD BART Config
      - bart_keys:/keys

  recovery-db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=noauth
      - POSTGRES_USER=nouser
      - POSTGRES_DB=alfresco_rec

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco

volumes:
  alfresco_root:
  bart_keys:
